"""add workspaces

Revision ID: ca82a5d7702b
Revises: 67857e385753
Create Date: 2026-09-30 16:08:20.326217
"""
from alembic import op
import sqlalchemy as sa


revision = 'ca82a5d7702b'
down_revision = '67857e385753'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analysis_runs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_analysis_runs_workspace_id'), 'analysis_runs', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'analysis_runs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_column('documents', 'workspace_id')
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=64),
               type_=sa.NUMERIC(precision=64),
               existing_nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'analysis_runs', type_='foreignkey')
    op.drop_index(op.f('ix_analysis_runs_workspace_id'), table_name='analysis_runs')
    op.drop_column('analysis_runs', 'workspace_id')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
