"""add document source fields (github)

Revision ID: b6861c4fa3ad
Revises: ca82a5d7702b
Create Date: 2026-09-30 16:39:25.056969
"""
from alembic import op
import sqlalchemy as sa


revision = 'b6861c4fa3ad'
down_revision = 'ca82a5d7702b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    is_sqlite = op.get_bind().dialect.name == "sqlite"
    if not is_sqlite:
        op.create_foreign_key(None, 'analysis_runs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('source_type', sa.String(length=32), nullable=True, server_default='upload'))
    op.add_column('documents', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('repo_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'repo_path')
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'source_type')
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=64),
               type_=sa.NUMERIC(precision=64),
               existing_nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'analysis_runs', type_='foreignkey')
    # ### end Alembic commands ###
