"""add document source fields (github)

Revision ID: b6861c4fa3ad
Revises: ca82a5d7702b
Create Date: 2026-09-30 16:39:25.056969

Fixed after the fact (the schema this produces is unchanged for databases that already ran it):

* upgrade() used to create the workspace foreign keys a second time (ca82a5d7702b already
  creates them), leaving two identical constraints (`..._fkey`, `..._fkey1`) on PostgreSQL. It now
  only creates a foreign key that is missing.
* downgrade() was autogenerated and could not run (`DROP CONSTRAINT` without a name). It now looks
  the constraints up and drops only the duplicate this migration may have added.
"""
from alembic import op
import sqlalchemy as sa


revision = 'b6861c4fa3ad'
down_revision = 'ca82a5d7702b'
branch_labels = None
depends_on = None


def _workspace_fk_names(table: str) -> list[str]:
    """Names of the foreign keys from `table.workspace_id` to workspaces, sorted."""
    inspector = sa.inspect(op.get_bind())
    return sorted(
        fk["name"]
        for fk in inspector.get_foreign_keys(table)
        if fk.get("name") and fk["referred_table"] == "workspaces" and fk["constrained_columns"] == ["workspace_id"]
    )


def upgrade() -> None:
    is_sqlite = op.get_bind().dialect.name == "sqlite"
    if not is_sqlite:
        for table in ("analysis_runs", "documents"):
            if not _workspace_fk_names(table):  # ca82a5d7702b normally created it already
                op.create_foreign_key(None, table, 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('source_type', sa.String(length=32), nullable=True, server_default='upload'))
    op.add_column('documents', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('repo_path', sa.Text(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table('documents') as batch:
        batch.drop_column('repo_path')
        batch.drop_column('source_url')
        batch.drop_column('source_type')

    if op.get_bind().dialect.name != "sqlite":
        # Databases migrated before upgrade() was fixed carry a duplicate foreign key (`..._fkey1`);
        # drop it and leave the original, which ca82a5d7702b's downgrade removes.
        for table in ("analysis_runs", "documents"):
            names = _workspace_fk_names(table)
            if len(names) > 1:
                for name in names[1:]:
                    op.drop_constraint(name, table, type_='foreignkey')
