"""add workspaces

Revision ID: ca82a5d7702b
Revises: 67857e385753
Create Date: 2026-09-30 16:08:20.326217
"""
from alembic import op
import sqlalchemy as sa


revision = 'ca82a5d7702b'
down_revision = '67857e385753'
branch_labels = None
depends_on = None


def upgrade() -> None:
    import sqlalchemy as sa
    from alembic import op
    from sqlalchemy.dialects import sqlite

    is_sqlite = op.get_bind().dialect.name == "sqlite"

    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analysis_runs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_analysis_runs_workspace_id'), 'analysis_runs', ['workspace_id'], unique=False)
    if not is_sqlite:
        op.create_foreign_key(None, 'analysis_runs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    if not is_sqlite:
        op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # The autogenerated version could not run (DROP CONSTRAINT without a name) and also converted
    # document_chunks.embedding to NUMERIC, which would have destroyed every stored vector.
    import sqlalchemy as sa
    from alembic import op

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    for table in ('documents', 'analysis_runs'):
        with op.batch_alter_table(table) as batch:
            if bind.dialect.name != "sqlite":
                for fk in inspector.get_foreign_keys(table):
                    if fk.get("name") and fk["referred_table"] == "workspaces" and fk["constrained_columns"] == ["workspace_id"]:
                        batch.drop_constraint(fk["name"], type_='foreignkey')
            batch.drop_index(op.f(f'ix_{table}_workspace_id'))
            batch.drop_column('workspace_id')
    op.drop_table('workspaces')
